Repository SpartaCodingClub-E1GHTEEN/Backend, pull requests merged in 2025-02, with the labels that each got.

#14 fix : 애플리케이션 실행 불가 오류 수정
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  src/main/java/com/sparta/first/project/eighteen/EighteenApplication.java
  src/main/java/com/sparta/first/project/eighteen/common/dto/ApiResponse.java
  src/main/java/com/sparta/first/project/eighteen/config/SecurityConfig.java
Labels: hotfix

#12 Feat/11
  .github/PULL_REQUEST_TEMPLATE.md
  .github/templates/BUG_ISSUE_TEMPLATE.md
  .github/templates/ETC_ISSUE_TEMPLATE.md
  .github/templates/FEATURE_ISSUE_TEMPLATE.md
  .github/workflows/test_pull_request.yml
  src/test/resources/application-test.yml
Labels: chore

#15 Feat/7
  src/main/java/com/sparta/first/project/eighteen/domain/stores/StoreController.java
  src/main/java/com/sparta/first/project/eighteen/domain/stores/dtos/StoreListResponseDto.java
  src/main/java/com/sparta/first/project/eighteen/domain/stores/dtos/StoreRequestDto.java
  src/main/java/com/sparta/first/project/eighteen/domain/stores/dtos/StoreResponseDto.java
  src/main/java/com/sparta/first/project/eighteen/domain/stores/dtos/StoreSearchDto.java
Labels: feat

#21 Feat#20
  src/main/java/com/sparta/first/project/eighteen/common/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/first/project/eighteen/domain/users/AdminController.java
  src/main/java/com/sparta/first/project/eighteen/domain/users/AuthController.java
  src/main/java/com/sparta/first/project/eighteen/domain/users/UserController.java
  src/main/java/com/sparta/first/project/eighteen/domain/users/dtos/UserRequestDto.java
  src/main/java/com/sparta/first/project/eighteen/domain/users/dtos/UserResponseDto.java
  src/main/java/com/sparta/first/project/eighteen/domain/users/dtos/UserSearchDto.java
  src/main/java/com/sparta/first/project/eighteen/domain/users/dtos/UserUpdateRequestDto.java
Labels: enhancement

#28 Feat/25
  src/main/java/com/sparta/first/project/eighteen/domain/reviews/ReviewRepository.java
  src/main/java/com/sparta/first/project/eighteen/model/reviews/Review.java
Labels: feat

#36 Feat/35
  src/main/java/com/sparta/first/project/eighteen/domain/reviews/ReviewRepository.java
  src/main/java/com/sparta/first/project/eighteen/domain/store/StoreRepository.java
  src/main/java/com/sparta/first/project/eighteen/domain/stores/StoreRepository.java
  src/main/java/com/sparta/first/project/eighteen/model/reviews/Review.java
  src/main/java/com/sparta/first/project/eighteen/model/stores/Store.java
Labels: feat

#38 Feat : UserRepository + UserEntity 구현
  src/main/java/com/sparta/first/project/eighteen/common/security/UserDetailsImpl.java
  src/main/java/com/sparta/first/project/eighteen/common/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/first/project/eighteen/config/SecurityConfig.java
  src/main/java/com/sparta/first/project/eighteen/domain/users/UserController.java
  src/main/java/com/sparta/first/project/eighteen/domain/users/UserRepository.java
  src/main/java/com/sparta/first/project/eighteen/domain/users/dtos/UserRequestDto.java
  src/main/java/com/sparta/first/project/eighteen/model/users/Role.java
  src/main/java/com/sparta/first/project/eighteen/model/users/SignUpType.java
  src/main/java/com/sparta/first/project/eighteen/model/users/User.java
  src/test/java/com/sparta/first/project/eighteen/domain/users/LoginTest.java
Labels: chore

#44 Feat: Payments Entity,Repository
  src/main/java/com/sparta/first/project/eighteen/domain/payments/PaymentsRepository.java
  src/main/java/com/sparta/first/project/eighteen/model/payments/Payments.java
Labels: feat

#52 Fix : AuditAware 수정
  src/main/java/com/sparta/first/project/eighteen/common/constants/Constant.java
  src/main/java/com/sparta/first/project/eighteen/config/AuditorAwareImpl.java
  src/main/java/com/sparta/first/project/eighteen/config/JpaConfig.java
Labels: hotfix

#53 Feat/43
  src/main/java/com/sparta/first/project/eighteen/common/exception/FoodException.java
  src/main/java/com/sparta/first/project/eighteen/common/exception/OrderException.java
  src/main/java/com/sparta/first/project/eighteen/common/exception/StoreException.java
  src/main/java/com/sparta/first/project/eighteen/common/exception/UserException.java
  src/main/java/com/sparta/first/project/eighteen/domain/orders/OrderController.java
  src/main/java/com/sparta/first/project/eighteen/domain/orders/OrderService.java
  src/main/java/com/sparta/first/project/eighteen/domain/orders/OrdersCustomRepository.java
  src/main/java/com/sparta/first/project/eighteen/domain/orders/OrdersRepository.java
  src/main/java/com/sparta/first/project/eighteen/domain/orders/OrdersRepositoryImpl.java
  src/main/java/com/sparta/first/project/eighteen/domain/orders/dtos/OrderCreateRequestDto.java
  src/main/java/com/sparta/first/project/eighteen/domain/orders/dtos/OrderDetailsOptionResponseDto.java
  src/main/java/com/sparta/first/project/eighteen/domain/orders/dtos/OrderDetailsRequestDto.java
  src/main/java/com/sparta/first/project/eighteen/domain/orders/dtos/OrderDetailsResponseDto.java
  src/main/java/com/sparta/first/project/eighteen/domain/orders/dtos/OrderDetailsUpdateRequestDto.java
  src/main/java/com/sparta/first/project/eighteen/domain/orders/dtos/OrderResponseDto.java
  src/main/java/com/sparta/first/project/eighteen/model/orders/OrderDetails.java
  src/main/java/com/sparta/first/project/eighteen/model/orders/OrderDetailsOptions.java
  src/main/java/com/sparta/first/project/eighteen/model/orders/Orders.java
  src/main/java/com/sparta/first/project/eighteen/model/orders/SortType.java
Labels: feat

#54 Feat/50-storeservice
  src/main/java/com/sparta/first/project/eighteen/domain/reviews/ReviewRepository.java
  src/main/java/com/sparta/first/project/eighteen/domain/stores/StoreController.java
  src/main/java/com/sparta/first/project/eighteen/domain/stores/StoreRepository.java
  src/main/java/com/sparta/first/project/eighteen/domain/stores/StoreService.java
  src/main/java/com/sparta/first/project/eighteen/domain/stores/dtos/StoreListResponseDto.java
  src/main/java/com/sparta/first/project/eighteen/domain/stores/dtos/StoreRequestDto.java
  src/main/java/com/sparta/first/project/eighteen/domain/stores/dtos/StoreResponseDto.java
  src/main/java/com/sparta/first/project/eighteen/domain/stores/dtos/StoreSearchDto.java
Labels: feat

#56 feat: FoodService 생성, 검색, 특정 메뉴 조회, 삭제 기능 구현 완료
  src/main/java/com/sparta/first/project/eighteen/domain/foods/FoodOptionsRepository.java
  src/main/java/com/sparta/first/project/eighteen/domain/foods/FoodsController.java
  src/main/java/com/sparta/first/project/eighteen/domain/foods/FoodsRepository.java
  src/main/java/com/sparta/first/project/eighteen/domain/foods/FoodsService.java
  src/main/java/com/sparta/first/project/eighteen/domain/foods/dtos/FoodCreateRequestDto.java
  src/main/java/com/sparta/first/project/eighteen/domain/foods/dtos/FoodGetResponseDto.java
  src/main/java/com/sparta/first/project/eighteen/domain/foods/dtos/FoodItemDto.java
  src/main/java/com/sparta/first/project/eighteen/domain/foods/dtos/FoodOptionRequestDto.java
  src/main/java/com/sparta/first/project/eighteen/domain/foods/dtos/FoodOptionResponseDto.java
  src/main/java/com/sparta/first/project/eighteen/domain/foods/dtos/FoodResponseDto.java
  src/main/java/com/sparta/first/project/eighteen/domain/foods/dtos/FoodSingleResponseDto.java
  src/main/java/com/sparta/first/project/eighteen/model/foods/FoodOptions.java
  src/main/java/com/sparta/first/project/eighteen/model/foods/Foods.java
Labels: feat

#65 Feat/60 admin service develop
  .github/workflows/test_pull_request.yml
  src/main/java/com/sparta/first/project/eighteen/domain/users/AdminController.java
  src/main/java/com/sparta/first/project/eighteen/domain/users/AdminService.java
  src/main/java/com/sparta/first/project/eighteen/domain/users/UserRepository.java
  src/main/java/com/sparta/first/project/eighteen/domain/users/UserSearchRepository.java
  src/main/java/com/sparta/first/project/eighteen/domain/users/UserSearchRepositoryImpl.java
  src/main/java/com/sparta/first/project/eighteen/domain/users/dtos/AdminUserSearchRequestDto.java
  src/main/java/com/sparta/first/project/eighteen/domain/users/dtos/AdminUserSearchResponseDto.java
  src/main/java/com/sparta/first/project/eighteen/domain/users/dtos/AdminUserUpdateRequestDto.java
  src/main/java/com/sparta/first/project/eighteen/domain/users/dtos/UserSortType.java
  src/main/java/com/sparta/first/project/eighteen/model/users/Users.java
  src/test/java/com/sparta/first/project/eighteen/domain/users/DeletedUserTest.java
  src/test/java/com/sparta/first/project/eighteen/domain/users/LoginTest.java
  src/test/resources/application-test.yml
Labels: refactor

#70 Feat/63 AI API 연동에 관련
  src/main/java/com/sparta/first/project/eighteen/domain/foods/FoodsController.java
  src/main/java/com/sparta/first/project/eighteen/domain/foods/FoodsService.java
  src/main/java/com/sparta/first/project/eighteen/domain/foods/dtos/FoodCreateRequestDto.java
  src/main/java/com/sparta/first/project/eighteen/domain/foods/dtos/FoodItemDto.java
  src/main/java/com/sparta/first/project/eighteen/domain/foods/dtos/FoodOptionRequestDto.java
  src/main/java/com/sparta/first/project/eighteen/domain/foods/dtos/FoodOptionResponseDto.java
  src/main/java/com/sparta/first/project/eighteen/domain/foods/dtos/FoodResponseDto.java
  src/main/java/com/sparta/first/project/eighteen/model/foods/Foods.java
  src/main/java/com/sparta/first/project/eighteen/utils/GeminiApiClient.java
  src/main/resources/data.sql
Labels: feat

#79 Refactor : 인가 방식 변경 및 액세스 토큰 발행일 검증 기능 추가
  .github/workflows/test_pull_request.yml
  src/main/java/com/sparta/first/project/eighteen/common/security/jwt/JwtAuthorizationFilter.java
  src/main/java/com/sparta/first/project/eighteen/common/security/jwt/JwtUtil.java
  src/main/java/com/sparta/first/project/eighteen/domain/users/AdminService.java
  src/main/java/com/sparta/first/project/eighteen/domain/users/UserService.java
  src/main/java/com/sparta/first/project/eighteen/domain/users/UsersIntegrationApp.java
  src/main/java/com/sparta/first/project/eighteen/model/users/Role.java
  src/main/java/com/sparta/first/project/eighteen/utils/UserUtils.java
  src/test/java/com/sparta/first/project/eighteen/domain/users/DeletedUserTest.java
  src/test/java/com/sparta/first/project/eighteen/domain/users/LoginTest.java
Labels: refactor

#84 Fix : Bean 초기화 문제 해결
  src/test/java/com/sparta/first/project/eighteen/domain/users/UsersIntegrationApp.java
Labels: hotfix

#92 Feat/76 리프레시 토큰 구현 추가
  src/main/java/com/sparta/first/project/eighteen/common/exception/UserException.java
  src/main/java/com/sparta/first/project/eighteen/common/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/first/project/eighteen/common/security/jwt/JwtAuthorizationFilter.java
  src/main/java/com/sparta/first/project/eighteen/common/security/jwt/JwtUtil.java
  src/main/java/com/sparta/first/project/eighteen/common/security/jwt/RefreshToken.java
  src/main/java/com/sparta/first/project/eighteen/config/SecurityConfig.java
  src/main/java/com/sparta/first/project/eighteen/domain/users/AuthController.java
  src/main/java/com/sparta/first/project/eighteen/domain/users/AuthService.java
  src/main/java/com/sparta/first/project/eighteen/domain/users/RefreshTokenRepository.java
  src/main/java/com/sparta/first/project/eighteen/model/users/TokenStatus.java
  src/main/java/com/sparta/first/project/eighteen/utils/UserUtils.java
  src/test/java/com/sparta/first/project/eighteen/domain/users/LoginTest.java
Labels: enhancement

#102 Feat : CORS 설정 추가
  src/main/java/com/sparta/first/project/eighteen/config/CorsConfig.java
  src/main/java/com/sparta/first/project/eighteen/config/SecurityConfig.java
Labels: chore
